### ISSUE TITLE
Integration tests and urlfetch

### ISSUE THREAD

**Issue by jonathan-s** [sigmavirus24/requests-toolbelt#134]
Since #119 has been merged I got curious about integration tests while using urlfetch. If you are calling urlfetch while in a testing environment you'll stumble upon the issue with an AssertionError:  `AssertionError: No api proxy found for service "urlfetch"`. 

Perhaps there could be another check in the [monkeypatch function](https://github.com/sigmavirus24/requests-toolbelt/blob/master/requests_toolbelt/adapters/appengine.py#L125) that prevents the monkeypatch if it is a test running.

**Comment by sigmavirus24** [comment]
> that prevents the monkeypatch if it is a test running. 

What does that mean? How would that detect if a test is running?

**Comment by jonathan-s** [comment]
The proposed way to execute tests for GAE is through this  [test runner](https://cloud.google.com/appengine/docs/python/tools/localunittesting?hl=en#Python_Setting_up_a_testing_framework) which means that `unittest` is imported in the beginning. 

So if there is a check like this in the monkeypatch function:
```
if 'unittest' not in sys.modules.keys():
        sessions.HTTPAdapter = AppEngineAdapter
```
It would fall back to normal requests instead of trying to monkeypatch sessions to use urlfetch which will cause trouble when executing it during a testing.

**Comment by jonathan-s** [comment]
It would probably be worth doing the check in AppEngineAdapter itself. Let me know if you think it would be worth implementing or if you see any issues with the approach.

**Comment by sigmavirus24** [comment]
Yeah, nothing else we support looks for unittest in `sys.modules` and I don't think we should start doing that. I would argue that your use of the monkeypatch function should be your business. We absolutely should not prevent anyone from using it in their test environment because there's no way to know what their needs are.

If you want a meta-monkeypatch function in your code base that does this check for you, that's great. We're not going to add that here.
