### ISSUE TITLE
app engine adapter asserts when path is missing or fragment is present

### ISSUE THREAD

**Issue by snarfed** [sigmavirus24/requests-toolbelt#141]
hi! first of all, thanks for requests-toolbelt and the app engine adapter. i'm excited to use it!

i recently upgraded from requests 2.1.0, which worked ok on app engine and used urlfetch, to requests 2.10.0 and requests-toolbelt 0.6.0, and so far so good! one minor glitch though: it asserts on URLs without a path or with a fragment. examples below.

is that intentional? i know path should always be provided and fragment omitted in the raw HTTP requests, but it's nice that requests handled this for me and i didn't have to sanitize URLs.

if this is a deliberate choice, that's fine, i can work around it. just curious. thanks in advance!

```py
from requests_toolbelt.adapters import appengine
appengine.monkeypatch()
requests.get('https://symmetricalsounds.withknown.com')
# or
requests.get('https://brid.gy/about#publish')
```

```py
File ".../requests/api.py", line 97, in head
  return request('head', url, **kwargs)
File ".../requests/api.py", line 57, in request
  return session.request(method=method, url=url, **kwargs)
File ".../requests/sessions.py", line 475, in request
  resp = self.send(prep, **send_kwargs)
File ".../requests/sessions.py", line 606, in send
  history = [resp for resp in gen] if allow_redirects else []
File ".../requests/sessions.py", line 179, in resolve_redirects
  **adapter_kwargs
File ".../requests/sessions.py", line 585, in send
  r = adapter.send(request, **kwargs)
File ".../requests/adapters.py", line 403, in send
  timeout=timeout
File ".../requests_toolbelt/adapters/appengine.py", line 104, in urlopen
  (self.url, url))
AssertionError: AppEngineConnection constructed with (https://symmetricalsounds.withknown.com), and called urlopen with (/). Expected the latter to be the host-relative equivalent of the former.

# or

AssertionError: AppEngineConnection constructed with (https://brid.gy/about#publish), and called urlopen with (/about). Expected the latter to be the host-relative equivalent of the former.
```

**Comment by sigmavirus24** [comment]
cc @mikelambert (the author of the adapter)

I think it makes sense to remove the assertion. Since we return a [new connection for *every* URL](https://github.com/sigmavirus24/requests-toolbelt/blob/d2cfc78697f48c9a72ba1e350f4bcfe8b6dddad8/requests_toolbelt/adapters/appengine.py#L69) then I don't think we really need to make assertions about the URLs in the request, especially since we [don't even use the one in the signature](https://github.com/sigmavirus24/requests-toolbelt/blob/d2cfc78697f48c9a72ba1e350f4bcfe8b6dddad8/requests_toolbelt/adapters/appengine.py#L109).

**Comment by mikelambert** [comment]
So the assertion was my attempt to make sure this API got used correctly, even on the adapted-GAE. Currently `urlopen(someurl)` will actually ignore `someurl`, and I didn't want obscure bugs being introduced as a result if people expected otherwise.

As the two URLs seemed to be the same from my reading of the code (I obviously missed your use cases!), I decided to be safe and assert that was the case. But @sigmavirus24 is correct that it doesn't really matter, so if he's down with removing the assert, I'm okay with it as well. (The alternative would be a more elaborate URL check than `endswith`.)
