### ISSUE TITLE
spliting the multipart contents through the boundaries has some problems with the final boundary

### ISSUE THREAD

**Issue by hyuen** [sigmavirus24/requests-toolbelt#161]
When splitting the body by using the boundary, there are some corner/edge cases that we could avoid by eliminating the last boundary. Here is how a document works:

--boundary

--boundary
.
.
--boundary--

The current code is splitting only on "--boundary", which gives a final element only with "--", I noticed that the check is that the final element is equal to "--\r\n", which is not robust enough. I ran into a problem where the final part was only "--" so I couldn't match it.

To fix this I am proposing eliminating the final marker: --boundary-- before doing the split. I am attaching the patch here:

```diff
diff --git a/requests_toolbelt/multipart/decoder.py b/requests_toolbelt/multipart/decoder.py
index 80b9678..41c6715 100644
--- a/requests_toolbelt/multipart/decoder.py
+++ b/requests_toolbelt/multipart/decoder.py
@@ -143,9 +143,13 @@ class MultipartDecoder(object):
             return BodyPart(fixed, self.encoding)
 
         def test_part(part):
-            return part != b'' and part != b'\r\n' and part[:4] != b'--\r\n'
+            return part and part != b'\r\n' and part[:4] != b'--\r\n'
+
+        # remove the final marker which is boundary + '--'
+        final_marker = b''.join((boundary, b'--'))
+        clean_content = self.content.replace(final_marker, '')
+        parts = clean_content.split(boundary)
 
-        parts = self.content.split(b''.join((b'\r\n', boundary)))
         self.parts = tuple(body_part(x) for x in parts if test_part(x))
 
     @classmethod
```

**Comment by hyuen** [comment]
Sorry, the patch got all messed up in the issue, here is the commit in my fork

https://github.com/hyuen/requests-toolbelt/commit/14600eaa3b5b9663624f39a2dd8390f7d60d8af4

Do you see any issues with this fix? are there ways to verify that there are no regressions?

Thanks

**Comment by sigmavirus24** [comment]
If you simply replace the final marker, then you're ignoring the 99% use-case where the end is `--boundary--\r\n`. What about doing:

```py
start_final_boundary = self.content.rfind('--boundary--')
clean_content = self.content[:start_final_boundary]
```

**Comment by hyuen** [comment]
How is that different from my patch? in your proposal you are looking for --boundary-- and ignoring everything from where we find it to the end of the string, in mine I am just supressing it, assuming that the message is conforming to standards, this end marker should be at the end of the string, no? I think both approaches could work.

Another question, how do I run the unit tests? I tried running nosetests and a lot of things are failing.

**Comment by sigmavirus24** [comment]
So let's be clear, whatever server you're talking to is not complying properly with `multipart/form-data` as specified by the corresponding RFC. It absolutely must end with `--boundary--\r\n`. If it doesn't then what's to stop it from ending with `--boundary--abc\r\n`?

If that's the case than calling `str.replace` will leave your final part with `abc\r\n` as part of it which is *wrong*. You don't want that junk data. Since we're explicitly parsing a `multipart/form-data` response body, stripping everything at the end is the *more* correct approach because it not only deals with the spec compliant version that this was written for, it handles the spec non-compliant server you're dealing with **and** servers sending junk data after the final boundary.

You run the unit tests either with `py.test` or with `tox`. Your choice but using tox will make your life easier as that's what we use and [document](http://toolbelt.readthedocs.io/en/latest/contributing.html#how-to-run-tests) for contributors.

**Comment by hyuen** [comment]
Hi, thanks for the clarification. I verified the problem I am facing, and it is slightly different from the one I was submitting the fix for.

What happens is that I have a message like this:
--boundary1
--boundary2
--boundary2
--boundary2


--boundary2--
--boundary1--

It is a nested multipart so not sure if it is conformant to any standard, the problem is that we expect "\r\n\r\n--boundary<x>", and there was only a single "\r\n" between the termination from boundary2 and boundary1 in this case. I fixed it by patching the response and adding an extra newline before --boundary1--.

I will check with the people working on the server and fix it on their side, but for now I think I don't need any fixes or hacks from this project.
