### ISSUE TITLE
MultipartEncoder slower than pure Requests and returning error

### ISSUE THREAD

**Issue by Wallboy** [sigmavirus24/requests-toolbelt#166]
Hello,

I'm having an issue with using MultipartEncoder to upload large files. First thing I'm noticing is that my upload is much slower than using pure requests.post() without a MultipartEncoder object. Second is that I'm getting back a 500 Internal Server error when using MultipartEncoder with the exact same data that works fine with the normal requests.post() call. Here is a snippet(edited) of my code: http://pastebin.com/zEwzFD1B

Why might these two requests be different when they should be both sending the same headers/body?

Thanks.

**Comment by Lukasa** [comment]
>  First thing I'm noticing is that my upload is much slower than using pure requests.post() without a MultipartEncoder object.

Yeah, unfortunately this is likely to happen. When you use Requests' built-in multipart support Requests builds the multipart body in memory and then sends it to the socket basically in one shot. So the low-level network behaviour is basically a tight-loop on the socket calling `send()` until the whole multipart body is complete. In fact, this tight loop is written in C in CPython, so it's *extremely* fast in comparison to executing Python code.

Unfortunately, the MultipartEncoder *does* execute Python code. httplib will issue 8192 byte read calls to the encoder, each one of which basically forces a whole lot of Python computation to work out where boundaries are and to call your callback. While all of this is going on there is no socket I/O happening, because all of the code here is purely synchronous (while we're in `socket.sendall()` we can't be in `read()`). That means that *inevitably* this will be much slower: there is vastly more Python code executing with the MultipartEncoder than there is with the regular multipart uploader.

For what it's worth, this problem is usually less visible on the open web, where the network latency is usually much larger than the latency involved in doing the Python computation.

As to why the internal server error is happening, the thing that seems most plausible is that with the MultipartEncoder your code doesn't seem to set the content-type header. This is really important, because it tells the server where the boundaries of the multipart types are. When using the MultipartEncoder, you need to add a `Content-Type` header with the value of `m.content_type`. Try that?

**Comment by sigmavirus24** [comment]
> When using the MultipartEncoder, you need to add a Content-Type header with the value of m.content_type.

This is absolutely the reason for your 500 response.

As for the speed, this is entirely `httplib`'s fault. Even if you passed a simple file object that was large to requests, you'd run into this same problem. We discussed this in #75. I even threw together #84, but we decided not to merge it here. We never got around to writing tests for that, but that *should* work. Feel free to use and adapt that as you wish.

**Comment by sigmavirus24** [comment]
It's also worth pointing out that both issues you encountered are documented in the section of our documentation dedicated to the MultipartEncoder: https://toolbelt.readthedocs.io/en/latest/uploading-data.html

The first example is

```py
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

m = MultipartEncoder(
    fields={'field0': 'value', 'field1': 'value',
            'field2': ('filename', open('file.py', 'rb'), 'text/plain')}
    )

r = requests.post('http://httpbin.org/post', data=m,
                  headers={'Content-Type': m.content_type})
```

And then we have a warning block that says:

> This object will end up directly in httplib. Currently, httplib has a hard-coded read size of 8192 bytes. This means that it will loop until the file has been read and your upload could take a while. This is not a bug in requests. A feature is being considered for this object to allow you, the user, to specify what size should be returned on a read. If you have opinions on this, please weigh in on [this issue](https://github.com/sigmavirus24/requests-toolbelt/issues/75).

**Comment by Wallboy** [comment]
Thanks guys,

I did wonder why the example specified the Content-Type again in the requests.post, and just totally assumed the content-type would be automatically determined from where I specified it in fields{}. This will definitely be the reason I was getting back 406/500 codes.

As far as the upload speed goes, I can max my 20 Mbit upload speed to my server using pure requests.post, but when I use the MultipartEncoder, it caps around 1.5-2 Mbit. Basically 10x slower.

I will take a look at the discussions you linked and run some tests with them. To get my upload progress for now though, I just create a new thread before the POST that uses request.get() to a JSON object that normally is used with AJAX to get my upload progress.
