### ISSUE TITLE
HTTPDigestAuth and MultipartEncoder

### ISSUE THREAD

**Issue by maxdeb** [sigmavirus24/requests-toolbelt#95]
Execution just blocks after executing the following with Python 3.4.0.
I am using the latest versions of requests and requests_toolbelt available in pip3.

```python
from requests.auth import HTTPDigestAuth
from requests_toolbelt.multipart.encoder import MultipartEncoder
import json
import requests

m = MultipartEncoder(fields={'field1': ('name', open('location/to/file', 'rb'), 'text/plain')})
authent = HTTPDigestAuth('USERNAME', 'PASSWORD')
r = requests.post(http://URL.com, auth=authent, data=m)
print(r.headers) 
print(r.status_code)
print(r.text)
```

**Comment by sigmavirus24** [comment]
How big is the file?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maxdeb** [comment]
My current testfile is 120KB, but it needs to be able to cope with 10MB
files if thats possible.

Without the digest implemented on server and clientside, everything worked
just fine. But now with the added digest, it doesn't.

**Comment by sigmavirus24** [comment]
So this sounds like a server issue. But keep in mind that Python's httplib is slow and will read 8192 bytes at a time to send to the server from files. So a 10 MB file will be slow. That said, I'm wondering if a flow like:

1. Authenticate
2. Upload file in a separate request

What happens with digest auth is:

1. Make request with body
2. Receive 401, respond to challenge
3. Continue

So what might be happening is that we're sending the whole file on the first request. The problem is that we can't know (and should never check) if you're using HTTPDigestAuth make the encoder a No-op. So this should be a workflow for your app. After the first authentication, the next authentication should be immediate if I remember Digest Auth appropriately.

**Comment by maxdeb** [comment]
Thanks for your reply, indeed, i need to send a first request with only auth info, and later send the whole request.
Maybe this is interesting to mention on your docs?

```python
from requests.auth import HTTPDigestAuth
from requests_toolbelt.multipart.encoder import MultipartEncoder
import json
import requests

m = MultipartEncoder(fields={'field1': ('name', open('location/to/file', 'rb'), 'text/plain')})
authent = HTTPDigestAuth('USERNAME', 'PASSWORD')
r = requests.post(http://URL.com, auth=authent)
r = requests.post(http://URL.com, auth=authent, data=m)
print(r.headers) 
print(r.status_code)
print(r.text)
```

**Comment by sigmavirus24** [comment]
Yeah, I think we'll want to update the docs with that as a corner case. Would you like to send a PR for that @maxdeb/
