### ISSUE TITLE
SourceAddressAdapter requires IP + port tuple

### ISSUE THREAD

**Issue by bui** [sigmavirus24/requests-toolbelt#96]
accidentally submitted this as shazow/urllib3#691

I think in addition to accepting a tuple, if just the IP string is passed then toolbelt should use a random available port so the user doesn't have to do all the guesswork :)

**Comment by sigmavirus24** [comment]
I'm assigning this to @Lukasa since the `SourceAddressAdapter` is his contribution. That said, I'm of the opinion that if the user knows they need that adapter, then they know enough to not have to do guesswork. If we start randomly choosing ports, we have a very real possibility of choosing one that is not available. This will lead to unpredictable bugs that will only be fixed by forcing the user to provide the port again.

**Comment by bui** [comment]
well, it seems the way [create_connection()](https://github.com/shazow/urllib3/blob/master/urllib3/util/connection.py#L59) handles it is by using port 0, would that work as a default?

**Comment by sigmavirus24** [comment]
So any changes like this are strictly backwards incompatible. Our documentation around the adapter is wrong, but it never worked the way it was documented anyway. It's always worked by taking a tuple. If we require an extra parameter, that will break a lot of people and I'd really rather not start adding a bunch of cases for different ways to handle the input.

**Comment by bui** [comment]
I don't think this would break anything

```python
    def __init__(self, source_address, **kwargs):
        if type(source_address) is str:
            self.source_address = (source_address, 0)
        else:
            self.source_address = source_address

        super(SourceAddressAdapter, self).__init__(**kwargs)
```

**Comment by Lukasa** [comment]
Eh, I think this is a reasonable enough thing to do, and we can do it pretty easily without breaking much. I don't think it'll be backward-incompatible: by semver it should go in a minor release, not a major one.
